sonar.projectKey=devsecops-simple-shop
sonar.projectName=DevSecOps Simple Shop
sonar.projectVersion=1.0
sonar.sources=server
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**
