sonar.projectKey=devsecops-simple-shop
sonar.projectName=DevSecOps Simple Shop
sonar.projectVersion=1.0
sonar.sources=server,public/js
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/public/images/**
