sonar.projectKey=devsecops-simple-shop
sonar.projectName=DevSecOps Project
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/.git/**,**/node_modules/**,**/reports/**,**/.deploy/**,**/k8s/**
