apiVersion: v1
kind: Service
metadata:
  name: ai-analyzer
  namespace: devsecops
  labels:
    app: ai-analyzer
spec:
  type: NodePort
  selector:
    app: ai-analyzer
  ports:
    - name: http
      port: 4300
      targetPort: 4300
      nodePort: 30430
      protocol: TCP
