apiVersion: 1

contactPoints:
  - orgId: 1
    name: lab-email
    receivers:
      - uid: lab-email-gmail
        type: email
        settings:
          addresses: naravanel31@gmail.com
          singleEmail: true
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: lab-email
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
